### ISSUE TITLE
請問一下 xxx 和 xxxSync 函數的差別是？

### ISSUE THREAD

**Issue by maple3142** [tongwentang/tongwen-core#2]
如題，在 source code 中看到了一些函數都是同步的，例如 `createSync`
但是為什麼還有另外的函數 `create` 回傳一個 Promise 包含了 `createSync` 的結果

**Comment by t7yang** [comment]
`create` 時因為會針對傳入的兩個物件進行分類重組，若物件比較大，同時段還有做其他事情的話怕會阻塞，所以就提供了一個非同步的版本。

**Comment by maple3142** [comment]
可是這不會因為這樣就變成非同步的...

**Comment by t7yang** [comment]
確實，應該是把每一個小步驟都非同步化才會有真的非同步效果，否則那整塊都同步的下一輪還是會塞住。所以那時候就有點懶得把細部的動作都拆成非同步（倒

**Comment by maple3142** [comment]
這個如果要非同步化的話需要使用 Worker(瀏覽器中) 或是其他和 Thread 有關的 library

**Comment by t7yang** [comment]
worker 當然最好，丟到另一個處理程序去處哩。但是初始化的部分是放在 background 執行的，這部分處理程序是受到控制，能不能夠開 worker 來跑我不是很確定。

**Comment by maple3142** [comment]
所以我覺得這不適合用非同步

**Comment by t7yang** [comment]
我當初的會這樣處理的思路應該是：瀏覽器啟動時，每個套件都要做初始化，所以如果他們的初始化都是同步的，就可以跳過讓他們先跑。後來都著重在開發功能傷，這塊就沒有想那麼多。

至於你說的不適合用非同步的是指那個部分，個別方法還是全部？

**Comment by maple3142** [comment]
這些東西從本質上來說只能同步的，因為都是一些運算而已
除非吧運算部分丟到 Thread 或是 Worker 之類的去運算
因為 js 本身是 single thread 的 
只要是在 main thread 上運算不管怎樣都會卡住

**Comment by t7yang** [comment]
沒錯，但是還是會有先後順序的問題。所以就像上面講的，思路是就算會塞也先讓別人做。我剛剛有看了一下其他套件的作法，似乎還真的有在用 worker 的，不過這個就要再花時間研究看看。如果你對這個部分造詣很高，就等你 PR。

**Comment by t7yang** [comment]
@maple3142 你說服我了，我暫時先在非同步的 API 拿掉。最近看一下，還是沒找到好的 worker 作法，之後實作出來再把非同步 API 加回去。
