### ISSUE TITLE
提交一处错误

### ISSUE THREAD

**Issue by poweryu** [tongwentang/tongwen-core#4]
t2s_phrase.json，第18行：

` "干乾": "康乾",`

应该是：
`康干`

**Comment by t7yang** [comment]
這字典檔的來源已不可考。所以這裡為什麼會這樣轉，現在來看也很奇怪。你方便提供一些範例是轉成「康干」的例子嗎？感謝。

**Comment by poweryu** [comment]
一般説“康乾盛世”而不説“干乾”盛世，所以我覺得是“康乾”。
我最近在把志蓮淨苑的南傳佛教佛經轉成簡體字，用tonwengtang發現有些詞轉的不太對，後續整理下發到這裏來。

**Comment by t7yang** [comment]
因為這個字典檔是針對舊演算法而設計的（裡面有分轉換用跟修飾用兩種對應），就只看這個詞彙，我覺得他是屬於修飾用的可能性比較高，因為「康」不太可能轉成「干」，所以我推測它是為了修飾「X干乾X」成「X康乾X」，但是我想不到任何例子。

針對新演算法，後續規劃出一個專門用來整理字典檔的 repo，到時如果你有時間的話，也歡迎參與整理的行列。

另外提供你一個訊息，網路上還有一套轉換工具——opencc，也是由一群（主要是中國人）有志之士開發的轉換工具，它的字典檔非常齊全，或許你可以考慮用它來轉。（新同文堂也在規劃未來使用 opencc 的字典檔）。

至於這個 issue 我就暫時先關閉，畢竟還沒有很確定這個轉換是錯誤的。若你後續有發現進一步可以確認的資料，我們就會馬上修正。感謝。

**Comment by poweryu** [comment]
好的
